### ISSUE TITLE
Delayed Ship Dates - FED Updates

### ISSUE THREAD

**Issue by lindseybradford** [lindseybradford/citizenry#311]
**Ticket:** [Delayed Ship Dates](https://app.asana.com/0/1114792018250928/1108553823152551)

**Branch:** `delayed-ship-dates-fed`

**Theme:** [delayed-ship-dates-fed](https://the-citizenry.myshopify.com/admin/themes/44274778185)

**Script:** [Handle Delayed Ship Dates](https://the-citizenry.myshopify.com/admin/apps/d25e45407e508f96409c2dd796e9bd95/scripts/45875273?hmac=372e3123da91290654be73095519b170fddc0ede20d7d16e055f85832b58e698&locale=en&shop=the-citizenry.myshopify.com&timestamp=1553010527) 

**Tasks:**

- [ ] Add highlight color. If a product has a value in the metafield `Alt_Shipping_Note`, apply color #ef7365 to the ship note in the following places: 

- shopping bag flyout 
- /cart page 
- all steps of checkout 
- order confirmation page 

- [ ] Make ship note styling consistent. In the **shopping bag flyout** update styling for both _default_ and `Alt_Shipping_Note` values as such:

- match italicized ship notes from **/cart** and **checkout**

- [ ] Add a sentence of copy to the **Shopify Order Confirmation email template**:

> For details on when these beauties will be headed home to you, click here. 

- Click here should dynamically link to individual user's order confirmation page.
